
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER E5-471
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tarik = new javax.swing.JButton();
        infosaldo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        infosaldo1 = new javax.swing.JButton();
        infosaldo2 = new javax.swing.JButton();
        tarik1 = new javax.swing.JButton();
        tarik2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tarik.setText(">");
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        getContentPane().add(tarik);
        tarik.setBounds(0, 230, 50, 37);

        infosaldo.setText("<");
        infosaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infosaldoActionPerformed(evt);
            }
        });
        getContentPane().add(infosaldo);
        infosaldo.setBounds(440, 230, 52, 37);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setText("EXIT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 230, 46, 29);

        infosaldo1.setText("<");
        infosaldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infosaldo1ActionPerformed(evt);
            }
        });
        getContentPane().add(infosaldo1);
        infosaldo1.setBounds(440, 90, 52, 37);

        infosaldo2.setText("<");
        infosaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infosaldo2ActionPerformed(evt);
            }
        });
        getContentPane().add(infosaldo2);
        infosaldo2.setBounds(440, 160, 52, 37);

        tarik1.setText(">");
        tarik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarik1ActionPerformed(evt);
            }
        });
        getContentPane().add(tarik1);
        tarik1.setBounds(0, 91, 50, 37);

        tarik2.setText(">");
        tarik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarik2ActionPerformed(evt);
            }
        });
        getContentPane().add(tarik2);
        tarik2.setBounds(0, 160, 50, 37);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel3.setText("INFO SALDO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 90, 120, 29);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel4.setText("TRANSFER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 160, 110, 29);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel5.setText("PENARIKAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 230, 140, 29);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel6.setText("PENYETORAN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 90, 150, 29);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel7.setText("BANTUAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 160, 101, 29);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        jLabel1.setText("LAKUKAN TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 340);

        setSize(new java.awt.Dimension(507, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null, "Terimakasih telah melakukan transaksi di ATM ");
        dispose();
        
    }//GEN-LAST:event_tarikActionPerformed

    private void infosaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infosaldoActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Penarikan().setVisible(true);
       
    }//GEN-LAST:event_infosaldoActionPerformed

    private void infosaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infosaldo1ActionPerformed
        // TODO add your handling code here:
        int saldo = 100000000;
        JOptionPane.showMessageDialog(null,"Saldo anda saat ini sebesar Rp "+saldo);
    }//GEN-LAST:event_infosaldo1ActionPerformed

    private void infosaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infosaldo2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new JFtransfer().setVisible(true);
       
      
    }//GEN-LAST:event_infosaldo2ActionPerformed

    private void tarik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarik1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new setor().setVisible(true);
    }//GEN-LAST:event_tarik1ActionPerformed

    private void tarik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarik2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Info().setVisible(true);
    }//GEN-LAST:event_tarik2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton infosaldo;
    private javax.swing.JButton infosaldo1;
    private javax.swing.JButton infosaldo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tarik;
    private javax.swing.JButton tarik1;
    private javax.swing.JButton tarik2;
    // End of variables declaration//GEN-END:variables
}
